From 7c126361812e47c23dfa14254588d81aa360e9a1 Mon Sep 17 00:00:00 2001
From: Bertrand Roussel <broussel@sierrawireless.com>
Date: Thu, 18 Oct 2018 00:36:56 -0700
Subject: [PATCH] Retry device_open without direct-io

For an unknown reason, it seems that the test for direct-io
in device_ready can pass while the same call in device_open fails.

Retry the device_open without direct-io in that case.

Signed-off-by: Bertrand Roussel <broussel@sierrawireless.com>
---
 lib/utils_device.c | 6 ++++++
 1 file changed, 6 insertions(+)

diff --git a/lib/utils_device.c b/lib/utils_device.c
index c98c835..4b26d5d 100644
--- a/lib/utils_device.c
+++ b/lib/utils_device.c
@@ -159,6 +159,12 @@ int device_open(struct device *device, int flags)
 
 	devfd = open(device_path(device), flags);
 
+	if ((devfd < 0) && device->o_direct && (errno == EINVAL))
+	{
+		log_dbg("Cannot open device %s with direct-io, retrying without.", device_path(device));
+		devfd = open(device_path(device), flags ^ O_DIRECT);
+	}
+
 	if (devfd < 0)
 		log_dbg("Cannot open device %s.", device_path(device));
 
-- 
2.19.1

